### ISSUE TITLE
discord-cannot accept invitation

### ISSUE THREAD

**Issue by xiaojia998** [kkatano/bakeneko-65#2]
discord-Invitation link seems to be expired, can't join, is it possible to x-invitation link now

**Comment by kkatano** [comment]
Can you join via the following link?
https://discord.gg/fMY96TeEwV

**Comment by xiaojia998** [comment]
![image](https://user-images.githubusercontent.com/60349831/111581605-8484d580-87f4-11eb-8e62-db7455cdd274.png)
Unable to accept invitation

**Comment by xiaojia998** [comment]
> 您可以通过以下链接加入吗？
> https://discord.gg/fMY96TeEwV

Successfully joined, thanks

**Comment by kkatano** [comment]
Thanks!
